### ISSUE TITLE
spn.structure.Base

### ISSUE THREAD

**Issue by zhengqigao** [steven-lang/spn-pytorch-experiments#28]
Hi, thanks for the SPN code! I am trying to run ``train_mnist.py`` and encountered the error: ``ModuleNotFoundError: No module named 'src.spn.structure'`` raised by Line 13 of file ``spn-pytorch-experiments/src/models/pytorch.py``.

I checked the folder content, and I cannot find it anywhere.

**Comment by braun-steven** [comment]
Hey @zhengqigao, since this repo is quite old, and I've moved to a more modern codebase, I can't really help you but point you to my https://github.com/braun-steven/simple-einet project.

Let me know if you have any questions over there.
